apiVersion: apps/v1
kind: Deployment
metadata:
  name: dispatcher-service-1
spec:
  template:
    spec:
      containers:
        - name: dispatcher-service-1
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: staging