apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-1
spec:
  template:
    spec:
      containers:
        - name: order-service-1
          resources:
            requests:
              memory: 756Mi
              cpu: "0.1"
            limits:
              memory: 756Mi
              cpu: "2"